### PR TITLE
Bootstrap Version Update to 3.4.1

### PR DESCRIPTION
**Pull request by nickumia-reisys**
I compared the files already existing in the repo to the updated (and new files) in the download from [official website](https://getbootstrap.com/docs/3.4/getting-started/#download.)  Using https://github.com/GSA/project-open-data-dashboard/commit/ff124b5adf7a70a6a5ef96d27408846bcc9d14e6 as a reference, I updated the relevant files in the same locations.  It seems like the Dashboard UI still looks the same and doesn't have any issues.  No known breaks.

### CODE REVIEW

**Review by FuhuXia — CHANGES_REQUESTED** [review]
this file should be ignored?
public/js/vendor/npm.js

**Comment by nickumia-reisys** [comment]
I saw it was a new file in the bootstrap download, but since it's not referenced anywhere, I guess we don't need it?

**Comment by FuhuXia** [comment]
> I saw it was a new file in the bootstrap download, but since it's not referenced anywhere, I guess we don't need it?

Yes let us remove it. Those referenced js files do not exist individually.

**Comment by nickumia-reisys** [comment]
> 
> 
> > I saw it was a new file in the bootstrap download, but since it's not referenced anywhere, I guess we don't need it?
> 
> Yes let us remove it. Those referenced js files do not exist individually.

Agreed 👍

**Review by FuhuXia — APPROVED** [review]

**Comment by mogul** [comment]
Do we need to PR this into the FCS branch to get it deployed there?

**Comment by FuhuXia** [comment]
> Do we need to PR this into the FCS branch to get it deployed there?

Yes we do, good call. https://github.com/GSA/project-open-data-dashboard/pull/350

**Pull request merged**
